<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
